version: '3.7'

services:
  x11-bridge:
    image: jare/x11-bridge
    container_name: x11-bridge
    volumes:
      - x11:/tmp/.X11-unix:rw
    ports:
      - "8080:8080"
    restart: always
    environment:
      MODE: tcp
      XPRA_HTML: "yes"
      DISPLAY: ":14"
      XPRA_TCP_PORT: "8080"
      XPRA_PASSWORD: password

  frontend:
    image: mintsrc/frontend:latest
    build:
      context: ./frontend/.devcontainer
      dockerfile: ./Dockerfile.node
    container_name: frontend
    hostname: frontend.local
    working_dir: /src
    environment:
      DISPLAY: ":14"
      LIBGL_ALWAYS_INDIRECT: 0
    depends_on:
      - x11-bridge
    volumes:
      - ./frontend:/src
      - x11:/tmp/.X11-unix:rw
    command: sleep infinity

  backend:
    image: mintsrc/backend:latest
    build:
      context: ./backend/.devcontainer
      dockerfile: ./Dockerfile.node
    container_name: backend
    hostname: backend.local
    working_dir: /src
    volumes:
      - ./backend:/src
      - ./frontend/src:/out
    command: sleep infinity

  postgres:
    image: postgres:14.1-alpine
    container_name: postgres
    hostname: postgres.local
    restart: always
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - '5432:5432'
    volumes:
      - pg:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    hostname: redis.local
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command:
      # Save if 100 keys are added in every 10 seconds
      - "--save 10 100"

volumes:
  pg:
    driver: local
  redis:
    driver: local
  x11:
    driver: local