/**
 * Generated by orval v6.8.1 🍺
 * Do not edit manually.
 * REST Api
 * Monolithic SaaS endpoints
 * OpenAPI spec version: 1.0
 */
import { rest } from 'msw';
import { faker } from '@faker-js/faker';

export const getAuthControllerLoginMock = () => ({
  accessToken: faker.random.word(),
});

export const getAuthControllerSignupMock = () => ({
  accessToken: faker.random.word(),
});

export const getAuthMSW = () => [
  rest.post('https://localhost:3000/auth/login', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getAuthControllerLoginMock()),
    );
  }),
  rest.post('https://localhost:3000/auth/signup', (_req, res, ctx) => {
    return res(
      ctx.delay(1000),
      ctx.status(200, 'Mocked status'),
      ctx.json(getAuthControllerSignupMock()),
    );
  }),
];
