/**
 * Generated by orval v6.9.0 🍺
 * Do not edit manually.
 * REST Api
 * Monolithic SaaS endpoints
 * OpenAPI spec version: 1.0
 */

export interface SignupRequest {
  email: string;
  username?: string;
  password: string;
  firstName: string;
  lastName: string;
}
